apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cht1b71o8-nodejs
  janus-idp.io/tekton: cht1b71o8-nodejs
  backstage.io/kubernetes-id: cht1b71o8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cht1b71o8-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
