apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: cht1b71o8-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cht1b71o8-nodejs 
  name: cht1b71o8-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cht1b71o8-nodejs
    weight: 100 
