apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cht1b71o8-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:3c868affbd1ca28918f7bcdb3f99b43ef5d2f2a0@sha256:4a833f2d670a7b3091be1010e77e2e1d978c66071f5b6441f197d73d5dde5e7d
          name: container-image
